# Generated by Django 4.2.4 on 2023-08-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0002_delete_individual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual_ref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(default=None, max_length=10)),
                ('nida_number', models.CharField(default=None, max_length=21)),
                ('address', models.CharField(default=None, max_length=20)),
                ('location', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
