# Generated by Django 4.2.4 on 2023-08-31 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_branch_individual_lending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual_lending',
            name='interest',
            field=models.FloatField(blank=True, default='0.0', null=True),
        ),
        migrations.RemoveField(
            model_name='individual_lending',
            name='referee',
        ),
        migrations.AlterField(
            model_name='individual_lending',
            name='returned_amount',
            field=models.FloatField(blank=True, default='0.0', null=True),
        ),
        migrations.AddField(
            model_name='individual_lending',
            name='referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.individual_ref'),
        ),
    ]
