# Generated by Django 4.2.4 on 2023-08-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_individual_lending_interest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual_lending',
            name='date_of_return',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individual_lending',
            name='lending_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
