# Generated by Django 4.2.4 on 2023-09-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_individual_lending_date_of_return_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(default=None, max_length=10)),
                ('nida_number', models.CharField(default=None, max_length=21)),
                ('address', models.CharField(default=None, max_length=20)),
                ('location', models.CharField(default=None, max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
