# Generated by Django 4.2.4 on 2023-09-02 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_group_lending'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='individual_ref',
            name='grou_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.my_group'),
        ),
        migrations.AddField(
            model_name='member',
            name='grou_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.my_group'),
        ),
    ]
