# Generated by Django 4.2.4 on 2023-09-02 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_my_group_individual_ref_grou_name_member_grou_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individual_ref',
            old_name='grou_name',
            new_name='group_name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='grou_name',
            new_name='group_name',
        ),
    ]
