# Generated by Django 4.2.4 on 2023-09-02 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_rename_grou_name_individual_ref_group_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_lending',
            name='group_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.my_group'),
        ),
    ]
