# Generated by Django 4.2.4 on 2023-09-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_group_lending_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual_ref',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='group_name',
        ),
        migrations.AlterField(
            model_name='group_lending',
            name='group_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='My_group',
        ),
    ]
