# Generated by Django 4.2.4 on 2023-09-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_alter_group_lending_group_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=200, null=True)),
                ('group_leader', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_registration', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
