# Generated by Django 4.2.4 on 2023-09-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_group_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group_info',
        ),
        migrations.AddField(
            model_name='my_group',
            name='date_of_registration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='my_group',
            name='group_leader',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
