# Generated by Django 4.2.4 on 2023-09-04 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_alter_branch_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual_ref',
            name='nida_number',
            field=models.CharField(default=None, max_length=20, validators=[django.core.validators.MaxLengthValidator(limit_value=20)]),
        ),
    ]
