from django.urls import path
from .import views
from .import admins

urlpatterns = [
    path('login_user',views.login_user,name='login_user'),
    path('logoutUser',views.logoutUser, name='logoutUser'),
    path('',views.home,name='home'),
    path('referee_individual',views.referee_individual,name='referee_individual'),
    path('delete_ref/<int:id>',views.delete_ref,name='delete_ref'),
    path('edit_ref/<int:id>',views.edit_ref,name='edit_ref'),
    path('view_referee/<int:id>', views.view_referee, name='view_referee'),
    path('individual_lending',views.individual_lending,name='individual_lending'),
    #url for return amount
    path('individual_lending/edit/', views.edit_individual_lending, name='edit_individual_lending'),
    path('edit_individual/<int:id>', views.edit_individual, name='edit_individual'),
    path('delete_individual/<int:id>', views.delete_individual, name='delete_individual'),
    path('view_individual/<int:id>', views.view_individual, name='view_individual'),
    #group functions starts here
    path('add_member',views.add_member,name='add_member'),
    path('delete_member/<int:id>', views.delete_member, name='delete_member'),
    path('member_edit/<int:id>', views.member_edit, name='member_edit'),
    path('member_lending',views.member_lending,name='member_lending'),
    path('member_lending_edit/<int:id>',views.member_lending_edit,name='member_lending_edit'),
    path('delete_member_lending/<int:id>',views.delete_member_lending,name='delete_member_lending'),
    path('group_lending/edit/', views.edit_group_lending, name='edit_group_lending'),
    path('view_group_info/<int:id>', views.view_group_info, name='view_group_info'),
    path('add_group',views.add_group,name='add_group'),
    path('delete_group/<int:id>',views.delete_group,name='delete_group'),
    path('group_edit/<int:id>',views.group_edit,name='group_edit'),

    #admin urls
    path('admin_home',admins.admin_home,name='admin_home'),
    path('add_branch',admins.add_branch,name='add_branch'),
    path('delete_branch/<int:id>',admins.delete_branch,name='delete_branch'),
    path('edit_branch/<int:id>',admins.edit_branch,name='edit_branch'),
    path('referee',admins.referee,name='referee'),
    path('delete_referee/<int:id>',admins.delete_referee,name='delete_referee'),
    path('edit_referee/<int:id>',admins.edit_referee,name='edit_referee'),
    path('manage_users',admins.manage_users,name='manage_users'),
    path('delete_users/<int:id>',admins.delete_users, name='delete_users'),
    path('lending_individual',admins.lending_individual,name='lending_individual'),
    path('lending_individual_update/edit/',admins.lending_individual_update, name='lending_individual_update'),
    path('delete_lending/<int:id>',admins.delete_lending, name='delete_lending'),
    path('update_individual_lending/<int:id>',admins.update_individual_lending, name='update_individual_lending'),
    path('view_lending/<int:id>',admins.view_lending, name='view_lending'),
    path('add_new_group',admins.add_new_group,name='add_new_group'),
    path('delete_group_info/<int:id>',admins.delete_group_info,name='delete_group_info'),
    path('new_group_edit/<int:id>',admins.new_group_edit,name='new_group_edit'),
    path('add_new_member',admins.add_new_member,name='add_new_member'),
    path('member_delete/<int:id>',admins.member_delete,name='member_delete'),
    path('new_member_edit/<int:id>',admins.new_member_edit,name='new_member_edit'),
    path('group_lending',admins.group_lending,name='group_lending'),
    path('delete_groups/<int:id>',admins.delete_groups,name='delete_groups'),
    path('return_loan/edit/',admins.return_loan, name='return_loan'),
    path('group_lending_edit/<int:id>',admins.group_lending_edit,name='group_lending_edit'),
    path('view_group_loan/<int:id>',admins.view_group_loan,name='view_group_loan'),
    path('edit_app/<int:id>',admins.edit_app,name='edit_app'),
    path('edit_app_status/<int:id>',admins.edit_app_status,name='edit_app_status'),
]
